apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth-redirect-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth-redirect-proxy
    app.kubernetes.io/part-of: spi-oauth-redirect-proxy-staging
  name: spi-oauth-redirect-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: spi-oauth-redirect-proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: spi-oauth-redirect-proxy
    spec:
      containers:
      - env:
        - name: ALLOWED_REDIRECT_URLS
          value: .opentlc.com,.openshiftapps.com,.ci.openshift.org
        image: quay.io/redhat-user-workloads-stage/rh-ee-abarbaro-tenant/spi-oauth-redirect-proxy-staging/spi-oauth-redirect-proxy@sha256:2f2d2028a853dd6fb156a712479046b339a5026cd49153bb3528274a0800a637
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
